# Generated by Django 5.2.7 on 2026-01-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100)),
                ('desscription', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('adresse', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('prix_par_nuit', models.FloatField()),
                ('capacite', models.PositiveIntegerField()),
                ('statut_logement', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('occupe', 'Occupé')], default='disponible', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to='logement.categorie')),
                ('propriteraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImangeLogement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logemnets/')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logement.logement')),
            ],
        ),
    ]
