# Generated by Django 5.2.7 on 2026-01-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logement',
            old_name='propriteraire',
            new_name='proprietaire',
        ),
        migrations.CreateModel(
            name='ImageLogement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logement.logement')),
            ],
        ),
        migrations.DeleteModel(
            name='ImangeLogement',
        ),
    ]
